import { Link, createFileRoute, useNavigate } from "@tanstack/react-router";
import { ArrowUpRight, Bookmark, ChevronRight, FileText, Headphones, MessageSquare, Play, Search, SlidersHorizontal, Video } from "lucide-react";
import { AuthedShell, SectionHeading } from "@/components/site-chrome";
import { useAuth } from "@/lib/auth";
import { cases, discussions, media, notes } from "@/lib/data";

export const Route = createFileRoute("/dashboard")({ component: DashboardPage });

const action = (label: string, to: "/cases" | "/board" | "/community" | "/media" | "/saved" | "/discussions" | "/notes") => <Link to={to} className="flex items-center gap-1 font-mono text-[0.65rem] tracking-[0.08em] text-brass hover:text-foreground">{label}<ArrowUpRight className="size-3" /></Link>;

function DashboardPage() {
  const { user, saved } = useAuth();
  const navigate = useNavigate();
  const lead = cases[0]!; const supporting = cases.slice(1, 3); const latest = discussions[0]!;
  return <AuthedShell><section className="mx-auto max-w-6xl px-5 py-10 md:px-10 md:py-12">
    <div className="animate-rise flex flex-wrap items-end justify-between gap-5"><div><div className="flex items-center gap-3 font-mono text-[0.62rem] tracking-[0.17em] uppercase text-muted-foreground"><span>Thursday, October 17, 2024</span><span className="live-dot size-2 rounded-full bg-ember" /><span>Live index</span></div><h1 className="mt-4 text-4xl sm:text-5xl">Good evening, {user?.name.split(" ")[0] || "Researcher"}.</h1><p className="mt-2 text-sm text-muted-foreground">Continue your research or see what the community is uncovering.</p></div><button className="flex items-center gap-2 border border-border bg-surface px-4 py-3 font-mono text-[0.65rem] tracking-[0.14em] uppercase text-muted-foreground hover:border-ember"><SlidersHorizontal className="size-4" />Filters <span className="bg-ember/70 px-1.5 py-0.5 text-primary-foreground">2</span></button></div>
    <form onSubmit={(e) => { e.preventDefault(); const q = (e.target as HTMLFormElement).querySelector('input')?.value?.toString().trim(); if (q) navigate({ to: '/search', search: { q } }); }} className="mt-9 flex border border-border bg-surface"><Search className="m-4 size-4 text-muted-foreground" /><input name="q" className="min-w-0 flex-1 bg-transparent text-sm text-foreground outline-none placeholder:text-muted-foreground" placeholder="Search case files, locations, names..." /><span className="m-2 hidden border border-border px-2 py-1 font-mono text-[0.6rem] text-muted-foreground sm:block">⌘ K</span></form>
    <div className="mt-11"><SectionHeading index="01" title="Active investigations" action={action("View all cases", "/cases")} /><article className="case-gradient grain relative overflow-hidden border border-border p-7 sm:p-9"><div className="relative z-10 max-w-xl"><div className="flex items-center gap-4 font-mono text-[0.62rem] tracking-[0.16em] uppercase"><span className="bg-ember/30 px-3 py-1.5 text-[#f2d9c8]">● Active investigation</span><span className="text-muted-foreground">Case ID / {lead.id}</span></div><h2 className="mt-8 text-5xl leading-[0.9] sm:text-6xl">The Vanishing at<br /><em className="text-brass">Blackwater</em></h2><p className="mt-4 font-mono text-[0.62rem] tracking-[0.1em] text-muted-foreground">{lead.location} · {lead.date}</p><div className="mt-10 max-w-xs"><div className="flex justify-between font-mono text-[0.6rem] tracking-[0.14em] uppercase text-muted-foreground"><span>Research progress</span><span className="text-brass">{lead.progress}%</span></div><div className="mt-2 h-1 bg-background/60"><div className="h-full bg-brass" style={{ width: `${lead.progress}%` }} /></div><div className="mt-2 flex justify-between font-mono text-[0.57rem] text-muted-foreground"><span>{lead.evidence.length} evidence items</span><span>{lead.suspects.length} suspects</span><span>{lead.timeline.length} timelines</span></div></div></div><Link to="/cases/$slug" params={{ slug: lead.slug }} className="relative z-10 mt-8 inline-flex items-center gap-3 bg-ember px-5 py-4 font-mono text-[0.65rem] tracking-[0.1em] text-primary-foreground sm:absolute sm:bottom-7 sm:right-7">Open case file <ArrowUpRight className="size-4" /></Link></article>
    <div className="mt-4 grid gap-4 md:grid-cols-2">{supporting.map((c) => <Link key={c.id} to="/cases/$slug" params={{ slug: c.slug }} className="dossier-card group overflow-hidden rounded bg-surface"><div className="h-24 bg-cover bg-center opacity-35 transition-opacity group-hover:opacity-55" style={{ backgroundImage: `url(${c.image})` }} /><div className="p-5"><div className="flex justify-between font-mono text-[0.6rem] tracking-[0.15em] uppercase"><span className={c.status === "active" ? "text-ember" : "text-brass"}>{c.status}</span><span className="text-muted-foreground">{c.id}</span></div><h3 className="mt-4 text-2xl transition-colors group-hover:text-brass">{c.title}</h3><p className="mt-1 font-mono text-[0.6rem] text-muted-foreground">{c.location}</p><div className="mt-4 flex justify-between border-t border-border pt-3 font-mono text-[0.6rem] text-muted-foreground"><span>{c.date}</span><Bookmark className="size-3" /></div></div></Link>)}</div></div>
    <div className="mt-11 grid gap-8 lg:grid-cols-[1.07fr_0.93fr]"><div><SectionHeading index="02" title="On the board" action={action("Open board", "/board")} /><Link to="/cases/$slug" params={{slug: lead.slug}} className="group block overflow-hidden border border-border bg-surface"><div className="relative h-48 overflow-hidden bg-[#1d2924] bg-[radial-gradient(#586d5d_1px,transparent_1px)] bg-[size:16px_16px]"><div className="absolute left-[28%] top-8 h-24 w-28 rotate-[-7deg] border-8 border-[#e5dcc4] bg-[#635d4a] shadow-xl" /><div className="absolute bottom-5 right-8 rotate-[8deg] bg-[#e8dbb8] px-4 py-3 font-mono text-[0.55rem] text-[#6b493b]">UNVERIFIED<br />RED PICKUP TRUCK</div><div className="absolute left-12 top-8 rotate-[-9deg] bg-[#ead9b8] px-3 py-2 font-mono text-[0.5rem] text-[#a04f40]">LAST SEEN<br />09.18.23 / 22:41</div></div><div className="flex items-center justify-between p-4 font-mono text-[0.62rem] text-ember"><span>◉ Evidence #08</span><ChevronRight className="size-4" /></div></Link></div><div><SectionHeading index="03" title="Latest from the community" action={action("All discussions", "/community")} /><article className="border border-border bg-surface p-5"><div className="flex items-start justify-between"><div className="flex gap-3"><span className="flex size-8 items-center justify-center bg-ember/60 font-mono text-[0.55rem] text-primary-foreground">{latest.initials}</span><div><p className="text-sm font-medium">{latest.author}</p><p className="font-mono text-[0.58rem] text-muted-foreground">{latest.lastActive} · {latest.tag} #{latest.id}</p></div></div><span className="text-muted-foreground">•••</span></div><h3 className="mt-6 text-2xl leading-tight">{latest.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{latest.body}</p><div className="mt-5 flex gap-4 border-t border-border pt-4 font-mono text-[0.6rem] text-muted-foreground"><span className="flex items-center gap-1"><MessageSquare className="size-3" />{latest.replies} replies</span><span>Last active {latest.lastActive}</span></div></article></div></div>
    <div className="mt-11"><SectionHeading index="04" title="Listen / Watch" action={action("Browse media", "/media")} /><div className="grid gap-4 md:grid-cols-2">{media.slice(0,2).map((item, i) => <article key={item.id} className="overflow-hidden border border-border bg-surface"><div className={`h-28 bg-cover bg-center ${i === 0 ? "bg-ember/35" : "bg-brass/25"}`} style={{backgroundImage:`linear-gradient(rgba(30,25,23,.35),rgba(30,25,23,.35)), url(${item.image})`}} /><div className="relative p-5"><div className="flex items-center gap-2 font-mono text-[0.6rem] tracking-[0.12em] uppercase text-brass">{item.kind === "podcast" ? <Headphones className="size-3"/> : <Video className="size-3"/>}{item.kind}</div><h3 className="mt-4 text-xl">{item.title}</h3><p className="mt-2 font-mono text-[0.6rem] text-muted-foreground">{item.source} · {item.duration}</p><button className="absolute bottom-5 right-5 flex size-8 items-center justify-center rounded-full border border-ember/50 bg-ember/20 text-ember"><Play className="size-3 fill-current" /></button></div></article>)}</div></div>
    <div className="mt-11"><SectionHeading index="04" title="Listen / Watch" action={action("Browse media", "/media")} /><div className="grid gap-4 md:grid-cols-2">{media.slice(0,2).map((item, i) => <article key={item.id} className="overflow-hidden border border-border bg-surface"><div className={`h-28 bg-cover bg-center ${i === 0 ? "bg-ember/35" : "bg-brass/25"}`} style={{backgroundImage:`linear-gradient(rgba(30,25,23,.35),rgba(30,25,23,.35)), url(${item.image})`}} /><div className="relative p-5"><div className="flex items-center gap-2 font-mono text-[0.6rem] tracking-[0.12em] uppercase text-brass">{item.kind === "podcast" ? <Headphones className="size-3"/> : <Video className="size-3"/>}{item.kind}</div><h3 className="mt-4 text-xl">{item.title}</h3><p className="mt-2 font-mono text-[0.6rem] text-muted-foreground">{item.source} · {item.duration}</p><button className="absolute bottom-5 right-5 flex size-8 items-center justify-center rounded-full border border-ember/50 bg-ember/20 text-ember"><Play className="size-3 fill-current" /></button></div></article>)}</div></div>
    <div className="mt-11"><SectionHeading index="05" title="Your workspace" />
      <div className="mt-6 grid gap-4 md:grid-cols-3">
        <Link to="/saved" className="dossier-card animate-rise rounded p-6 [animation-delay:100ms]">
          <div className="flex items-center justify-between">
            <span className="flex items-center gap-2 font-mono text-[0.65rem] tracking-[0.18em] uppercase text-ember"><Bookmark className="size-4" />Saved cases</span>
            <ArrowUpRight className="size-4 text-muted-foreground" />
          </div>
          <p className="mt-3 font-display text-3xl text-foreground">{saved.length}</p>
          <p className="mt-1 text-xs text-muted-foreground">Cases you’re tracking</p>
        </Link>
        <Link to="/discussions" className="dossier-card animate-rise rounded p-6 [animation-delay:180ms]">
          <div className="flex items-center justify-between">
            <span className="flex items-center gap-2 font-mono text-[0.65rem] tracking-[0.18em] uppercase text-ember"><MessageSquare className="size-4" />My discussions</span>
            <ArrowUpRight className="size-4 text-muted-foreground" />
          </div>
          <p className="mt-3 font-display text-3xl text-foreground">{discussions.length}</p>
          <p className="mt-1 text-xs text-muted-foreground">Threads you’re involved in</p>
        </Link>
        <Link to="/notes" className="dossier-card animate-rise rounded p-6 [animation-delay:260ms]">
          <div className="flex items-center justify-between">
            <span className="flex items-center gap-2 font-mono text-[0.65rem] tracking-[0.18em] uppercase text-ember"><FileText className="size-4" />Private notes</span>
            <ArrowUpRight className="size-4 text-muted-foreground" />
          </div>
          <p className="mt-3 font-display text-3xl text-foreground">{notes.length}</p>
          <p className="mt-1 text-xs text-muted-foreground">Research notes only you can see</p>
        </Link>
      </div>
    </div>
    {saved.length > 0 && <div className="mt-10 border-t border-border pt-5 font-mono text-[0.6rem] tracking-[0.14em] uppercase text-muted-foreground">{saved.length} saved case{saved.length > 1 ? "s" : ""} · {notes.length} private notes · Index synced just now</div>}
  </section></AuthedShell>;
}
