/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BoardRouteImport } from './routes/board'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiscussionsRouteImport } from './routes/discussions'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MediaRouteImport } from './routes/media'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityIdRouteImport } from './routes/community.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsRoute = DiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/community/$id',
  path: '/community/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/dashboard': typeof DashboardRoute
  '/discussions': typeof DiscussionsRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/community/$id': typeof CommunityIdRoute
  '/cases/': typeof CasesIndexRoute
  '/community/': typeof CommunityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/dashboard': typeof DashboardRoute
  '/discussions': typeof DiscussionsRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/community/$id': typeof CommunityIdRoute
  '/cases': typeof CasesIndexRoute
  '/community': typeof CommunityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/dashboard': typeof DashboardRoute
  '/discussions': typeof DiscussionsRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/community/$id': typeof CommunityIdRoute
  '/cases/': typeof CasesIndexRoute
  '/community/': typeof CommunityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/board'
    | '/dashboard'
    | '/discussions'
    | '/faq'
    | '/login'
    | '/media'
    | '/notes'
    | '/privacy'
    | '/saved'
    | '/search'
    | '/settings'
    | '/signup'
    | '/submit'
    | '/terms'
    | '/cases/$slug'
    | '/community/$id'
    | '/cases/'
    | '/community/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/board'
    | '/dashboard'
    | '/discussions'
    | '/faq'
    | '/login'
    | '/media'
    | '/notes'
    | '/privacy'
    | '/saved'
    | '/search'
    | '/settings'
    | '/signup'
    | '/submit'
    | '/terms'
    | '/cases/$slug'
    | '/community/$id'
    | '/cases'
    | '/community'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/board'
    | '/dashboard'
    | '/discussions'
    | '/faq'
    | '/login'
    | '/media'
    | '/notes'
    | '/privacy'
    | '/saved'
    | '/search'
    | '/settings'
    | '/signup'
    | '/submit'
    | '/terms'
    | '/cases/$slug'
    | '/community/$id'
    | '/cases/'
    | '/community/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BoardRoute: typeof BoardRoute
  DashboardRoute: typeof DashboardRoute
  DiscussionsRoute: typeof DiscussionsRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  NotesRoute: typeof NotesRoute
  PrivacyRoute: typeof PrivacyRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
  CasesSlugRoute: typeof CasesSlugRoute
  CommunityIdRoute: typeof CommunityIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions': {
      id: '/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof DiscussionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/community/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BoardRoute: BoardRoute,
  DashboardRoute: DashboardRoute,
  DiscussionsRoute: DiscussionsRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  NotesRoute: NotesRoute,
  PrivacyRoute: PrivacyRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
  CasesSlugRoute: CasesSlugRoute,
  CommunityIdRoute: CommunityIdRoute,
  CasesIndexRoute: CasesIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
